Enforce cargo v1.75

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -3,13 +3,23 @@
 # Pre-push hook script to run code quality checks and ensure consistency.
 #
 # This script will execute two custom scripts located in the `scripts/` directory:
-# 1. clippy-on-all-workspaces.sh: Runs Clippy, tests, and formatting on all specified workspaces.
-# 2. sv2-header-check.sh: Ensures the `sv2.h` file generated by `build_header.sh` matches the
+# 1. Enforce cargo version 1.75.
+# 2. clippy-on-all-workspaces.sh: Runs Clippy, tests, and formatting on all specified workspaces.
+# 3. sv2-header-check.sh: Ensures the `sv2.h` file generated by `build_header.sh` matches the
 #    committed version.
 
 # Exit immediately if any command exits with a non-zero status and print each command before
 # executing it.
 set -xe
+
+# Enforce cargo version 1.75
+REQUIRED_CARGO_VERSION="1.75.0"
+INSTALLED_CARGO_VERSION=$(cargo --version | awk '{print $2}')
+
+if [ "$INSTALLED_CARGO_VERSION" != "$REQUIRED_CARGO_VERSION" ]; then
+    echo "Error: Cargo version $REQUIRED_CARGO_VERSION is required. Installed version is $INSTALLED_CARGO_VERSION."
+    exit 1
+fi
 
 # Run clippy, test, and rustfmt on all workspaces
 sh ./scripts/clippy-fmt-and-test.sh
